spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/peekster
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8089
  
jwt:
  auth:
    converter:
      resource-id: my-security-test-app
      principle-attribute: preferred_username